version: '3.8'

services:
  web:
    build: .
    command: ["/src/docker_commands/gunicorn.sh"]
    container_name: delivery_web
    env_file:
      - .env
    volumes:
      - .:/src
    depends_on:
    - db
    restart: always
    ports:
      - 8000:8000

  db:
    image: postgres:15-alpine
    container_name: delivery_db
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
#    user: ${UID}:${GID}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    container_name: delivery_db_pgadmin
    image: dpage/pgadmin4:6.15
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  pgadmin: