# Generated by Django 4.2.1 on 2023-05-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('location_delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_to', to='core.location')),
                ('location_pickup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_from', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('number', models.CharField(db_index=True, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.SmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.location')),
            ],
        ),
    ]
